### PR TITLE
Simplify API, fix package structure, simplify parsing.

### LINKED ISSUE #22: dhcp6: move most options to another package
The API is bloated because of all of the available options, and it really shows in the godoc page especially.  Most unusual options should be moved to another package.

### PR DESCRIPTION
**Pull request by hugelgupf**
Closes #22.

- Cleaned up parsing code. No more magic numbers and manual indexing.
- Options moved to their own package.
- Server moved to its own package.
- All tests passing. 

It may be easier to explore these changes here: https://github.com/hugelgupf/dhcp6/tree/simplify-api

### CODE REVIEW

**Comment by hugelgupf** [comment]
Cleaned up lint warnings and all that for each commit.

**Comment by mdlayher** [comment]
It looks like you've incorporated the idea of functions that accept the options map, and the buffer change is a good idea instead of having to manually take care of all the offsets.

Thanks for doing this. I don't believe I'll have time to do a comprehensive review until Monday, but I think I like the direction that I am seeing.

**Comment by hugelgupf** [comment]
See also the equivalent in DHCPv4: https://github.com/hugelgupf/dhcp4

File: options.go [hunk 1]
```diff
@@ -41,684 +28,118 @@ func (o Options) Add(key OptionCode, value encoding.BinaryMarshaler) error {
...
-			return nil, true, err
-		}
-
-		iapd[i] = ia
-	}
-
-	return iapd, true, nil
-}
+// Marshal writes options into the provided Buffer sorted by option codes.
+func (o Options) Marshal(b *util.Buffer) {
```
Comment (mdlayher) [inline options.go]: Is there any way we can not expose the buffer type?  I feel like it belongs in an internal package, and that this function should just have the usual `MarshalBinary() ([]byte, error)` signature.

File: options.go [hunk 2]
```diff
@@ -41,684 +28,118 @@ func (o Options) Add(key OptionCode, value encoding.BinaryMarshaler) error {
...
-// ArchType values could not be parsed from the option.
-func (o Options) NII() (*NII, bool, error) {
-	v, ok := o.Get(OptionNII)
-	if !ok {
-		return nil, false, nil
-	}
+// It is used with various different types to enable parsing of both top-level
+// options, and options embedded within other options. If options data is
+// malformed, it returns ErrInvalidOptions.
+func (o *Options) Unmarshal(buf *util.Buffer) error {
```
Comment (mdlayher) [inline options.go]: Same, but `UnmarshalBinary(b []byte) error`.

File: options_test.go [hunk 3]
```diff
@@ -2,2130 +2,149 @@ package dhcp6
...
-			if want, got := tt.err, err; want != got {
-				t.Fatalf("[%02d] test %q, unexpected error for Options.NII(): %v != %v",
-					i, tt.desc, want, got)
-			}
-
+		value, err := tt.options.GetOne(tt.key)
+		if want, got := tt.err, err; want != got {
+			t.Errorf("[%02d] test %q, unexpected err for Options.GetOne(%v): %v != %v",
+				i, tt.desc, tt.key, want, got)
+		} else if err != nil {
```
Comment (mdlayher) [inline options_test.go]: I think this is cleaner without the `else if` block, and more obvious that all error handling is occurring at the next level of indentation.

File: options_test.go [hunk 4]
```diff
@@ -2263,25 +282,25 @@ func Test_parseOptions(t *testing.T) {
...
-				t.Fatalf("[%02d] test %q, unexpected error for parseOptions(%v): %v != %v",
-					i, tt.desc, tt.buf, want, got)
-			}
-
+		var options Options
+		err := (&options).Unmarshal(util.NewBuffer(tt.buf))
+		if want, got := tt.err, err; want != got {
+			t.Errorf("[%02d] test %q, unexpected error for parseOptions(%v): %v != %v",
+				i, tt.desc, tt.buf, want, got)
+		} else if err != nil {
```
Comment (mdlayher) [inline options_test.go]: Same.

File: opts/miscoptions.go [hunk 5]
```diff
@@ -220,34 +231,33 @@ func (u *URL) UnmarshalBinary(b []byte) error {
 // ArchTypes is a slice of ArchType values.  It is provided for convenient
 // marshaling and unmarshaling of a slice of ArchType values from an Options
 // map.
-type ArchTypes []ArchType
+type ArchTypes []dhcp6.ArchType
```
Comment (mdlayher) [inline opts/miscoptions.go]: Let's also move ArchType to this package.

File: opts/options.go [hunk 6]
```diff
@@ -0,0 +1,415 @@
...
+
+	s := new(StatusCode)
+	err = s.UnmarshalBinary(v)
+	return s, err
+}
+
+// GetRapidCommit returns the Rapid Commit Option value, described in RFC 3315,
+// Section 22.14.
+//
+// The boolean return value indicates if OptionRapidCommit was present in the
```
Comment (mdlayher) [inline opts/options.go]: This documentation is no longer true.

File: opts/options_test.go [hunk 7]
```diff
@@ -0,0 +1,1825 @@
...
+	}
+
+	for i, tt := range tests {
+		// DUID parsing is tested elsewhere, so errors should automatically fail
+		// test here
+		duid, err := GetClientID(tt.options)
+		if want, got := tt.err, err; want != got {
+			t.Errorf("[%02d] test %q, unexpected err for dhcp6.Options.ClientID(): %v != %v",
+				i, tt.desc, want, got)
+		} else if err != nil {
```
Comment (mdlayher) [inline opts/options_test.go]: Same as other tests re: indentation and else if, and same throughout the file.

File: util/buffer.go [hunk 8]
```diff
@@ -0,0 +1,140 @@
+package util
+
+import (
+	"encoding/binary"
+)
+
+var order = binary.BigEndian
```
Comment (mdlayher) [inline util/buffer.go]: `const`

File: util/buffer.go [hunk 9]
```diff
@@ -0,0 +1,140 @@
+package util
```
Comment (mdlayher) [inline util/buffer.go]: I don't think a "util" package is a good idea, and would prefer something like `internal/buffer` instead.  Then the constructor becomes `buffer.New()`.

As mentioned previously, I also think that the buffer type should only be an implementation detail within the package, and that any exported marshaling and unmarshaling functions should use the stdlib interfaces, even if they use a buffer underneath.

**Comment by mdlayher** [comment]
Also note the travis build failures.

File: util/buffer.go (hunk 8 above)
Comment (hugelgupf) [reply util/buffer.go]: binary.BigEndian is not a const.

File: options.go (hunk 1 above)
Comment (hugelgupf) [reply options.go]: This is similar to the optslice.write([]byte) function you had previously -- it avoids having to allocate all options in one buffer and then copying that buffer to the "parent" buffer.

The only reason this has to be exported is because of the usage in dhcp6opts. Otherwise, even Marshal and Unmarshal could be implementation details of this package.

(I'll push a commit to change this to what you want, but I'd prefer to revert it.)

**Comment by hugelgupf** [comment]
Should be all done now. Thanks for the review!

**Comment by hugelgupf** [comment]
Can you take a look at the Travis failure? I think it has to do with the Travis setup rather than the PR.

**Comment by mdlayher** [comment]
Not sure what the problem is!  Going to merge as is and see if that remedies things, since we moved some packages around.
